### ISSUE TITLE
$led Bug: Brackets with tags starting in '$' will not submit properly, players with $ in name get renamed

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#1]
This can be seen in SKTAR3 with $led and Rowan SSBM #2 with $man<>boi

when clicking submit the 'Are you sure' dialogue comes up like normal, but clicking submit on that will not do anything

this happens if you're creating a new player or tagging them with an existing alias 

another example of a bug with $: http://njssbm.com/#/newjersey/tournaments/57072e64e5925764360756d8
from here http://chaoticneutral.challonge.com/chaoticneutralweeklymelee4_7

Pizza$ was renamed to _cel when submitted

It does not seem to happen with Ko$a (because its in the middle I assume)

**Comment by jhertz** [comment]
chris, can you test this out more? make a fake tourney on challonge and see if it doesnt work, a minimal testcase would be gr8

**Comment by jessemtso** [comment]
this bug may not exist anymore. further investigation is required.

**Comment by jessemtso** [comment]
punting on this for a bit

**Comment by jhertz** [comment]
confirmed this bug has been fixed.

**Comment by VestboyMyst** [comment]
$led bug strikes again

https://www.notgarpr.com/#/newjersey/tournaments/57749d38e592572285c2b886

fppssbm.challonge.com/smashheist3

wont let me submit with $legit$ as a new player

**Comment by BrandonCookeDev** [comment]
So this is still an issue? I'm not sure where this is activating in the code but I can try to look into it

**Comment by jhertz** [comment]
Apparently it is. We should write a unit test that imports a challonge bracket with lots of ppl with $ in their names and stuff, make sure it works. 


Ask @vestboy_myst if its still an issue

**Comment by jschnei** [comment]
I can't reproduce this locally.

**Comment by VestboyMyst** [comment]
maybe it was another issue with that bracket? ill try submitting it again

**Comment by VestboyMyst** [comment]
nope still getting the error on the above bracket url

submit prompt appears but nothing happens when i click it, and $legit$ is always the only entry that is both unchecked and has nothing in its 'player search' field when i first load the page

**Comment by jschnei** [comment]
So basically, this is happening: https://github.com/angular/angular.js/issues/1463 .

For reasons like this, we should basically never pass names around as keys of dicts/objects (there is a similar problem with json/python for names that start with ".").

**Comment by jschnei** [comment]
Should be closed by #83. (@VestboyMyst let me know if weird stuff still happens).
